spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # password: 1234
    # url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tsi
    url: jdbc:mysql://localhost:3306/tsi
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: Message
    consumer:
      group-id: messageId
      key-deserializer: org.apache.kafka.common.serialization.ShortDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      group-id: messageId
      key-serializer: org.apache.kafka.common.serialization.ShortSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


